# Generated by Django 5.0.1 on 2024-01-10 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterialInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Paleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.classification')),
            ],
        ),
        migrations.CreateModel(
            name='PaletaInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('paleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.paleta')),
            ],
        ),
        migrations.CreateModel(
            name='MerchandiseMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_inventory', models.IntegerField()),
                ('final_inventory', models.IntegerField()),
                ('movement_date', models.DateTimeField()),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.rawmaterialinventory')),
            ],
        ),
    ]
